Item refactor
iTNTPiston/botw-hundo-dupl pull request #1
Opened 2022-07-06 16:55 UTC by elduende05

- all missing materials and key items
- animated icons with menu option
- localization of item descriptions
- item registration cleanup

2022-07-07 04:20 UTC, iTNTPiston requested changes
See my comments.

2022-07-07 04:20 UTC, iTNTPiston commented on src/core/Item.ts
>      Lotus = "Lotus",
We don't really want to allow duplicated enums for the same material, since users may take advantage of this, and we will break existing scripts when we remove this.

2022-07-07 04:20 UTC, iTNTPiston commented on src/core/Item.ts
> +	// Default id to 0 if undefined in config file
Id is completely unused now. Can remove id from config file completely

2022-07-07 04:20 UTC, iTNTPiston commented on src/core/Item.ts
> +	return Object.entries(ItemType).find(([key]) => key === type)?.[1];
Can we use something clearer here? `ItemType[type]` should give you the enum value by name

2022-07-07 04:20 UTC, iTNTPiston commented on src/core/Slots.ts
> +			if(data.type === ItemType.Key || item === Item.MasterSword || item === Item.MasterSwordAwakened) {
Does the game treat Master Sword and Master Sword Awakened as 2 separate weapons? AFAIK the upgrade part is just a flag. If we treat them as separate, this can become buggy during the duplication check (or we have to add extra logic)

2022-07-07 04:20 UTC, iTNTPiston commented on src/App.tsx
> +	const [animatedIcons, setAnimatedIcons] = useState<boolean>(false);
nit - can we call this `isIconAnimated` to indicate it's a flag?

2022-07-07 04:20 UTC, iTNTPiston commented on src/config/i18n/en_US.json
> +{
Did you generate this from yaml? If so, can include the yaml source since we can use a webpack loader to load yaml files directly in the future

2022-07-07 04:24 UTC, elduende05 commented on src/config/i18n/en_US.json
> +{
I added this directly as json by grabbing the list of items, regexing it to roughly the form that was needed, then going in and adding spaces / formatting the display values as appropriate.

2022-07-07 04:27 UTC, elduende05 commented on src/core/Slots.ts
> +			if(data.type === ItemType.Key || item === Item.MasterSword || item === Item.MasterSwordAwakened) {
I'm not actually sure. Same with enabled / disabled versions of the champion abilities. Would require testing in game or perhaps asking leoetlino or kinak in the discord. Maybe for these we could leave the icons in for now, remove the item registration for them, then come back later to add options to mark the MS as awakened or not and enable / disable each champ ability?

2022-07-07 04:28 UTC, elduende05 commented on src/core/Item.ts
> +	return Object.entries(ItemType).find(([key]) => key === type)?.[1];
If something seems weird to you, it's probably my lack of familiarity with JS syntax in general or TS specifically. I'll see if what you suggested works.

2022-07-07 04:28 UTC, elduende05 commented on src/core/Item.ts
> +	// Default id to 0 if undefined in config file
I'll go cull it from the config file and remove the associated code.

2022-07-07 04:29 UTC, elduende05 commented on src/core/Item.ts
>      Lotus = "Lotus",
Should I just leave the enum registered with the short names like "Lotus" for now but convert its existence elsewhere (image file name)?

2022-07-07 04:30 UTC, elduende05 commented on src/core/Localization.ts
> +	return Object.entries(display).find(([key]) => key === displayKey)?.[1] || defaultValue || displayKey;
Lack of familiarity with syntax. I'll try what you suggested.

2022-07-07 04:32 UTC, elduende05 commented on src/App.tsx
> +	const [animatedIcons, setAnimatedIcons] = useState<boolean>(false);
Sure thing.

2022-07-07 06:33 UTC, iTNTPiston commented on src/core/Slots.ts
> +			if(data.type === ItemType.Key || item === Item.MasterSword || item === Item.MasterSwordAwakened) {
Sure

2022-07-07 07:52 UTC, elduende05 commented on src/core/Item.ts
> +	return Object.entries(ItemType).find(([key]) => key === type)?.[1];
That expression does not appear to work.

2022-07-07 09:29 UTC, elduende05 commented on src/core/Item.ts
> +	return Object.entries(ItemType).find(([key]) => key === type)?.[1];
`(<any>ItemType)[type]` seems to work

2022-07-07 11:38 UTC, elduende05 commented on src/core/Item.ts
>      Lotus = "Lotus",
I took the above approach.

2022-07-07 12:22 UTC, elduende05 commented on src/core/DisplayableInventory.ts
> +    animatedImage?: string,
Figured something out, although the amount of code change seems to be about the same since I have to pass the animatedIcons option around a bit more up top.

2022-07-07 12:24 UTC, elduende05 commented
I think I've addressed all your concerns. I kept the review feedback separate for now, but if you think this looks ok I can squash the changes down into the appropriate commits.

2022-07-08 05:59 UTC, iTNTPiston requested changes

2022-07-08 05:59 UTC, iTNTPiston commented on src/core/Item.ts
> +	register(itemData.item as Item, (<never>ItemType)[itemData.type], itemData.options);
Generally it's a bad idea to use `never` or `any`. The linter is going to complain. One of the ways to solve casting is have a type declaration for the entire `itemList` structure, like `type ItemDataObject = { ... }`. This way we also get some documentation of what the json type is supposed to be

2022-07-08 05:59 UTC, iTNTPiston commented on src/core/Localization.ts
> +	return (<never>display)[displayKey] ?? defaultValue ?? displayKey;
`type LanguageMap = Record<string, string>;`, then you can cast `display` to that and not have wacky types

2022-07-09 03:07 UTC, elduende05 commented on src/core/Item.ts
> +	register(itemData.item as Item, (<never>ItemType)[itemData.type], itemData.options);
I see. I can try to put something like that in place. Certainly nice to have some type safety.

2022-07-09 03:07 UTC, elduende05 commented on src/core/Localization.ts
> +	return (<never>display)[displayKey] ?? defaultValue ?? displayKey;
Nice. I'll try that.

2022-07-13 23:50 UTC, iTNTPiston approved these changes

2022-07-14 00:26 UTC, elduende05 commented on src/App.css
> +  padding:1px;
The items actually have a small amount of padding in game and some of the icons looked weird stretched all the way to the border (the saddles and bridles mostly). Try removing it and comparing those last few key items to see the effect, but it was actually true for all items throughout the inventory. Originally I started updating the images but then realized you kinda don't want to pre-bake your padding if you don't need to. It would have also taken forever to do that for all 500+ icons.

2022-07-14 02:23 UTC, merged