Drop weapons, bows, and shields instead of reducing durability
iTNTPiston/botw-hundo-dupl pull request #11
Opened 2022-08-04 04:07 UTC by jordanbtucker

This fixes an issue where weapons, bows, and shields that have increased durability were having their durability values reduced when the `Drop` command was used without specifying its `life` meta value.

For example:

```
Get 1 Weapon[life=80000] 1 Bow[life=80000] 1 Shield[life=80000]
Drop 1 Weapon 1 Bow 1 Shield
```

was resulting in:

```
Initialize 1 Weapon[life=79000] 1 Bow[life=79000] 1 Shield[life=79000]
```

when it should empty the inventory instead.

Tests are included.

Fixes #10

2022-08-04 20:11 UTC, iTNTPiston requested changes

2022-08-04 20:11 UTC, iTNTPiston commented on src/core/Slots/Slots.ts
> +					if(stack.item.type === ItemType.Weapon || stack.item.type === ItemType.Bow || stack.item.type === ItemType.Shield){
This will only work for `Drop 1 Bow` right? If you do `Drop 2 Bow` it would only drop 1 of them since it doesn't respect `toRemove.count`

2022-08-04 20:11 UTC, iTNTPiston commented on src/core/Slots/Slots.ts
> +					if(stack.item.type === ItemType.Weapon || stack.item.type === ItemType.Bow || stack.item.type === ItemType.Shield){
Also please add unit tests to `Slots.remove.test.ts`

2022-08-05 00:51 UTC, jordanbtucker commented on src/core/Slots/Slots.ts
> +					if(stack.item.type === ItemType.Weapon || stack.item.type === ItemType.Bow || stack.item.type === ItemType.Shield){
> This will only work for `Drop 1 Bow` right? If you do `Drop 2 Bow` it would only drop 1 of them since it doesn't respect `toRemove.count`

Nope. Given the command:

```
Drop 1 Weapon 2 Bow 2 Shield
```

`parseCommand` will parse this as three `ItemStackCommandWrapper`s:

```json5
[
  {number: 1, stack: {life: 1000, item: {id: 'Weapon'}}},
  {number: 2, stack: {life: 1000, item: {id: 'Bow'}}},
  {number: 2, stack: {life: 1000, item: {id: 'Shield'}}},
]
```

When `CommandRemove` executes on the state, `processWrappers` will call `getStackAndSlotCount` on each wrapper and, since none of these items are `stackable`, will return five `ItemStack`s:

```json5
[
  {life: 1000, item: {id: 'Weapon'}},
  {life: 1000, item: {id: 'Bow'}},
  {life: 1000, item: {id: 'Bow'}},
  {life: 1000, item: {id: 'Shield'}},
  {life: 1000, item: {id: 'Shield'}},
]
```

Each of these `ItemStack`s will be removed individually by `Slots.remove`.

> Also please add unit tests to `Slots.remove.test.ts`

Will do.

2022-08-05 00:59 UTC, iTNTPiston commented on src/core/Slots/Slots.ts
> +					if(stack.item.type === ItemType.Weapon || stack.item.type === ItemType.Bow || stack.item.type === ItemType.Shield){
Sounds good. I forgot how that system works. I should probably go back and add some more documentation lol

2022-08-05 01:00 UTC, iTNTPiston approved these changes

2022-08-05 01:03 UTC, merged