Basic tests
iTNTPiston/botw-hundo-dupl pull request #3
Opened 2022-07-17 19:04 UTC by savage13

Added 3 tests:
- Basic Orb Duping
  - Taken from the initial data on statup
- Getting 999 Apples
- Getting 999 Apples and many Orbs

Note: I needed to use `Sync GameData` to make sure the basic orb duping test worked as result had a difference between the `Game Data` and `Visible Inventory`.  Is there a set the `Game Data` differently than the `Visible Inventory`? Or am I thinking about this incorrectly?

2022-07-17 20:21 UTC, iTNTPiston requested changes
We don't have a command that initializes gamedata to be different yet. I think im going to make that now. You can change the tests once that's there

2022-07-17 20:21 UTC, iTNTPiston commented on src/__tests__/apples_999.e2e.ts
> +// Author: Swiffy22
change this to Savage13

2022-07-17 20:21 UTC, iTNTPiston commented on src/__tests__/apples_orbs.e2e.ts
> +// Author: Swiffy22
change this to Savage13

2022-07-17 20:21 UTC, iTNTPiston commented on src/__tests__/dup_orbs.e2e.ts
> +// Author: Swiffy22
change this to Savage13

2022-07-17 20:51 UTC, iTNTPiston commented on src/__tests__/apples_999.e2e.ts
> +// Author: Swiffy22
or savage13 idk which one you prefer

2022-07-17 20:56 UTC, savage13 commented on src/__tests__/apples_orbs.e2e.ts
> +// Author: Swiffy22
Done

2022-07-17 20:56 UTC, savage13 commented on src/__tests__/apples_999.e2e.ts
> +// Author: Swiffy22
Done

2022-07-17 20:56 UTC, savage13 commented on src/__tests__/dup_orbs.e2e.ts
> +// Author: Swiffy22
Done

2022-07-19 08:08 UTC, iTNTPiston commented
I'm a bit confused about the commit history, looks like you have some commits duplicated? Can you try rebase on latest main?

2022-07-21 12:37 UTC, closed without merging